pip install colorama
pip install win10toast
pip install json
pip install requests
pip install datetime
pip install discord
pip install selenium
pip install psutil
pip install emoji
pip install typing
